### ISSUE TITLE
Fiscal Year 2023-2024 and 2024-2025 not displayed on CKAN platform

### ISSUE THREAD

**Issue by Prajna1999** [Prajna1999/ocds-ckan#3]
In the CKAN portal fiscalYear field remains empty for FY 23-24 and FY 24-25. 

Possible causes:
1. The ocid and id field are messed up during generating OCDS mapping. Running update endpoint patches multiple tenders with same id and ocid.
2. The OCDS JSON files are corrupted making entire CKAN tender database erroneous.

**Comment by AakashGandhi1** [comment]
I have updated the zip file. Previously, it only contained the JSON files that I used to address the fiscal year update issue on CKAN. Regarding the "id" field, it's intended for scenarios where multiple tenders share the same tender ID. Since most tenders have only one associated tender, it appears as "1." This matches how we've represented the data on CKAN in the past.

**Comment by Prajna1999** [comment]
Update @AakashGandhi1 explicitly updating Fiscal Year in the CKAN platform itself works for FY 23-24. Seems to me the only way is to run the script to manually is to sort all the JSON by fiscal year, hardcode for 23-24 and 24-25 and run the update script. Can you run that script once and let me know if it works or not?
